import React, { useState } from 'react';
import { EvidenceBasedRecommendation } from '../../types';
import {
  FileText,
  CheckCircle2,
  BrainCircuit,
  TrendingUp,
  Filter,
  Layers,
  Sparkles,
  Info,
  ExternalLink,
  ShieldCheck,
  Building,
  Calendar,
  Tag
} from 'lucide-react';
import { EvidenceBadge, EvidenceLegend, ConfidenceBadge, normalizeClaimType } from '../common/EvidenceBadge';

interface EvidenceAnalysisViewProps {
  recommendations: EvidenceBasedRecommendation[];
}

export const EvidenceAnalysisView: React.FC<EvidenceAnalysisViewProps> = ({
  recommendations,
}) => {
  const [filterType, setFilterType] = useState<string>('ALL');

  const filtered = filterType === 'ALL'
    ? recommendations
    : recommendations.filter((r) => {
        const { type } = normalizeClaimType(r.basis || r.provenance);
        return type === filterType;
      });

  const sourceCount = recommendations.filter((r) => normalizeClaimType(r.basis || r.provenance).type === 'SOURCE').length;
  const inferenceCount = recommendations.filter((r) => normalizeClaimType(r.basis || r.provenance).type === 'INFERENCE').length;
  const projectionCount = recommendations.filter((r) => normalizeClaimType(r.basis || r.provenance).type === 'PROJECTION').length;

  return (
    <div className="space-y-6" id="evidence-analysis-section">
      {/* Header Bar */}
      <div className="p-5 sm:p-6 rounded-2xl bg-gradient-to-br from-[#121520] to-[#0A0C12] border border-zinc-800 space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 text-xs font-semibold tracking-wider uppercase text-[#D6A84F] font-tech">
              <FileText className="w-4 h-4" />
              <span>Evidence & Source Intelligence Layer</span>
            </div>
            <h2 className="text-xl sm:text-2xl font-bold text-white mt-1 font-cinematic">
              Evidence-Based Analysis Matrix
            </h2>
            <p className="text-xs sm:text-sm text-zinc-300 mt-1 max-w-3xl leading-relaxed">
              Every major claim generated by CineScout is strictly classified to maintain complete analytical transparency. Forward projections are explicitly distinguished from verified historical benchmarks.
            </p>
          </div>

          {/* Provenance Filter Pills */}
          <div className="flex flex-wrap items-center gap-1.5 p-1 rounded-xl bg-black/60 border border-zinc-800 self-start sm:self-center shrink-0">
            <button
              type="button"
              onClick={() => setFilterType('ALL')}
              className={`px-3 py-1.5 rounded-lg text-xs font-tech font-bold uppercase transition-colors ${
                filterType === 'ALL'
                  ? 'bg-[#D6A84F] text-black'
                  : 'text-zinc-400 hover:text-white'
              }`}
            >
              All ({recommendations.length})
            </button>
            <button
              type="button"
              onClick={() => setFilterType('SOURCE')}
              className={`px-3 py-1.5 rounded-lg text-xs font-tech font-bold uppercase transition-colors flex items-center gap-1.5 ${
                filterType === 'SOURCE'
                  ? 'bg-emerald-500 text-black'
                  : 'text-zinc-400 hover:text-emerald-400'
              }`}
            >
              <CheckCircle2 className="w-3 h-3" />
              <span>Source ({sourceCount})</span>
            </button>
            <button
              type="button"
              onClick={() => setFilterType('INFERENCE')}
              className={`px-3 py-1.5 rounded-lg text-xs font-tech font-bold uppercase transition-colors flex items-center gap-1.5 ${
                filterType === 'INFERENCE'
                  ? 'bg-sky-500 text-black'
                  : 'text-zinc-400 hover:text-sky-400'
              }`}
            >
              <BrainCircuit className="w-3 h-3" />
              <span>Inference ({inferenceCount})</span>
            </button>
            <button
              type="button"
              onClick={() => setFilterType('PROJECTION')}
              className={`px-3 py-1.5 rounded-lg text-xs font-tech font-bold uppercase transition-colors flex items-center gap-1.5 ${
                filterType === 'PROJECTION'
                  ? 'bg-amber-500 text-black'
                  : 'text-zinc-400 hover:text-amber-400'
              }`}
            >
              <TrendingUp className="w-3 h-3" />
              <span>Projection ({projectionCount})</span>
            </button>
          </div>
        </div>

        {/* Global Evidence Standard Legend */}
        <EvidenceLegend />
      </div>

      {/* Cards List */}
      <div className="grid grid-cols-1 gap-5">
        {filtered.map((item, idx) => {
          const claim = normalizeClaimType(item.basis || item.provenance);
          const isSource = claim.type === 'SOURCE';
          const hasSourceDetails = item.sourceDetails && item.sourceDetails.sourceTitle;

          return (
            <div
              key={item.id || idx}
              className="p-5 sm:p-6 rounded-2xl bg-[#0D0F18] border border-zinc-800/90 hover:border-zinc-700 transition-all duration-200 space-y-4 shadow-lg"
            >
              {/* Card Header: Title + Category + Claim Badge + Confidence */}
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-zinc-800/80">
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <span className="text-[10px] font-bold text-[#D6A84F] uppercase tracking-wider font-tech px-2 py-0.5 rounded bg-[#D6A84F]/10 border border-[#D6A84F]/20">
                      {item.category} Intelligence
                    </span>
                    <ConfidenceBadge level={item.confidence || 'HIGH'} />
                  </div>
                  <h3 className="text-base sm:text-lg font-bold text-white font-cinematic">
                    {item.title}
                  </h3>
                </div>

                <div className="flex items-center gap-2 self-start sm:self-center shrink-0">
                  <EvidenceBadge basis={item.basis || item.provenance} size="sm" />
                </div>
              </div>

              {/* Verified Source Attribution Banner (When Source-Backed) */}
              {isSource && (
                <div className="p-3 sm:p-4 rounded-xl bg-emerald-950/20 border border-emerald-500/30 space-y-2">
                  <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-emerald-400 font-tech">
                    <CheckCircle2 className="w-3.5 h-3.5" />
                    <span>Verified External Evidence Citation</span>
                  </div>

                  <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-2 pt-1 text-xs">
                    <div className="p-2 rounded-lg bg-black/40 border border-emerald-500/20">
                      <span className="text-[10px] text-zinc-400 uppercase font-tech block mb-0.5">Source Title</span>
                      <span className="font-semibold text-white truncate block">
                        {item.sourceDetails?.sourceTitle || 'Verified Industry Benchmark Report'}
                      </span>
                    </div>

                    <div className="p-2 rounded-lg bg-black/40 border border-emerald-500/20">
                      <span className="text-[10px] text-zinc-400 uppercase font-tech block mb-0.5">Source Type</span>
                      <span className="font-medium text-emerald-300 truncate block">
                        {item.sourceDetails?.sourceType || 'Industry Benchmark & Field Data'}
                      </span>
                    </div>

                    <div className="p-2 rounded-lg bg-black/40 border border-emerald-500/20">
                      <span className="text-[10px] text-zinc-400 uppercase font-tech block mb-0.5">Organization / Archive</span>
                      <span className="font-medium text-zinc-200 truncate block">
                        {item.sourceDetails?.organization || item.sourceDetails?.publication || 'AFRIFF / Nollywood Guild Archive'}
                      </span>
                    </div>

                    <div className="p-2 rounded-lg bg-black/40 border border-emerald-500/20 flex flex-col justify-between">
                      <span className="text-[10px] text-zinc-400 uppercase font-tech block mb-0.5">Reference Link</span>
                      {item.sourceDetails?.url ? (
                        <a
                          href={item.sourceDetails.url}
                          target="_blank"
                          rel="noreferrer noopener"
                          className="text-[#D6A84F] hover:underline flex items-center gap-1 font-tech font-semibold text-[11px]"
                        >
                          <span>Open Resource</span>
                          <ExternalLink className="w-3 h-3" />
                        </a>
                      ) : (
                        <span className="text-zinc-500 text-[11px] font-tech">Institutional Record</span>
                      )}
                    </div>
                  </div>
                </div>
              )}

              {/* Unverified / AI Projection Banner (When External Evidence Unavailable) */}
              {!isSource && (
                <div className="p-2.5 rounded-lg bg-zinc-950/60 border border-zinc-800 text-[11px] font-tech text-zinc-400 flex items-center justify-between gap-2">
                  <div className="flex items-center gap-2">
                    <Info className="w-3.5 h-3.5 text-sky-400 shrink-0" />
                    <span>
                      {claim.type === 'PROJECTION'
                        ? 'External empirical baseline unavailable — this finding represents a forward-looking AI projection.'
                        : 'Deduced via structured analytical inference from screenplay mechanics and filmmaker parameters.'}
                    </span>
                  </div>
                  <span className="text-[10px] text-zinc-500 uppercase font-semibold hidden md:inline">
                    Strict Transparency Standard
                  </span>
                </div>
              )}

              {/* 3-Part Structure: Evidence -> Analysis -> Recommendation */}
              <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
                {/* 1. Evidence */}
                <div className="p-4 rounded-xl bg-black/50 border border-zinc-800 flex flex-col justify-between">
                  <div>
                    <div className="flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-zinc-300 font-tech mb-2">
                      <span className="w-1.5 h-1.5 rounded-full bg-zinc-400" />
                      <span>1. Core Evidence / Signal</span>
                    </div>
                    <p className="text-xs text-zinc-200 leading-relaxed font-sans">
                      {item.evidence}
                    </p>
                  </div>
                  <div className="mt-3 pt-2 border-t border-zinc-800/80 text-[10px] text-zinc-500 font-tech">
                    {isSource ? 'Verified empirical baseline' : 'Primary analytical observation'}
                  </div>
                </div>

                {/* 2. Analysis */}
                <div className="p-4 rounded-xl bg-black/50 border border-zinc-800 flex flex-col justify-between">
                  <div>
                    <div className="flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-sky-400 font-tech mb-2">
                      <span className="w-1.5 h-1.5 rounded-full bg-sky-400" />
                      <span>2. Industry Analysis</span>
                    </div>
                    <p className="text-xs text-zinc-200 leading-relaxed font-sans">
                      {item.analysis}
                    </p>
                  </div>
                  <div className="mt-3 pt-2 border-t border-zinc-800/80 text-[10px] text-zinc-500 font-tech">
                    Analytical deduction & commercial implication
                  </div>
                </div>

                {/* 3. Recommendation */}
                <div className="p-4 rounded-xl bg-emerald-950/20 border border-emerald-500/30 flex flex-col justify-between">
                  <div>
                    <div className="flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-emerald-400 font-tech mb-2">
                      <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" />
                      <span>3. Prescribed Action</span>
                    </div>
                    <p className="text-xs text-zinc-100 font-medium leading-relaxed font-sans">
                      {item.recommendation}
                    </p>
                  </div>
                  <div className="mt-3 pt-2 border-t border-emerald-900/40 text-[10px] text-emerald-400/80 font-tech">
                    Direct instruction for creative & packaging team
                  </div>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};

